



Name: Kartik Khurana  




## Section A — Theory

ANS.1

In simple terms, `==` compares the values of two objects. `is` checks whether both variables are pointing to the same object.

So two lists can contain exactly the same values and still give `False` with `is`.

ANS.2

A mutable object can be changed after it is created. An immutable object cannot be changed directly.



| list | Mutable
| tuple | Immutable |
| set | Mutable |
| dict | Mutable |
| str | Immutable |
| int | Immutable |
| float | Immutable |
| bool | Immutable |
| frozenset | Immutable |

This difference is useful because it tells us whether an existing object can be modified or whether a new object has to be created.

ANS.3

This happens because decimal floating values are not always stored exactly in binary. The computer stores a very close value of `0.1` and `0.2`, so their result can be slightly different from `0.3`.

That is why direct equality checks with floating values can sometimes be surprising.

ANS.4

A tuple is a good choice when the data is not supposed to change.

For example, coordinates such as `(28.61, 77.20)` can naturally be stored in a tuple. Tuples are also useful when returning several values from a function. If the tuple contains only hashable values, it can also be used as a dictionary key.

ANS.5

Python dictionaries are designed so that a key can usually be taken directly to its stored value instead of checking every item one by one.

Internally, this is done using a hash table structure. Because of this, finding a key is normally O(1) on average, although there can be slower cases when collisions occur.

ANS.6

`range()` is a normal Python tool and is mainly used when we need a sequence of integers, especially in loops.

`numpy.arange()` creates a NumPy array and is useful for numerical work. It can also be used with a non-integer step such as `0.2`.

ANS.7

These three list methods all add something, but they do it differently:

- `append(x)` puts `x` at the end as one item.
- `extend(x)` adds the elements of `x` one by one.
- `insert(i, x)` puts `x` at a particular position.

The difference becomes especially clear when `x` is another list.

ANS.8

In `a, *b, c = [10, 20, 30, 40, 50]`, the first value goes to `a`, the last value goes to `c`, and all the values in between go into the list `b`.

So the result is `a = 10`, `b = [20, 30, 40]`, and `c = 50`.

If Python does not have enough values for the required positions, it raises `ValueError`.

ANS.9

These operators have different jobs:

- `/` → normal division
- `//` → floor division
- `%` → remainder
- `**` → power



ANS.10

NumPy is built for numerical calculations. Its arrays store data more efficiently, and many operations run in optimized compiled code instead of doing everything through a Python loop.



## Section B — Output Prediction

ANS.11



In [ ]:
# [[99, 0, 0], [0, 0, 0], [0, 0, 0]]
# [[99, 0, 0], [99, 0, 0], [99, 0, 0]]


matrix1 = [[0] * 3 for _ in range(3)]
matrix2 = [[0] * 3] * 3

matrix1[0][0] = 99
matrix2[0][0] = 99

print(matrix1)
print(matrix2)

[[99, 0, 0], [0, 0, 0], [0, 0, 0]]
[[99, 0, 0], [99, 0, 0], [99, 0, 0]]


ANS.12



In [ ]:
# x = [1, 2, 3, 4]
# y = [1, 2, 3]
# a = [1, 2, 3, 4]
# b = [1, 2, 3, 4]



x = [1, 2, 3]
y = x
x = x + [4]
print("x =", x)
print("y =", y)

a = [1, 2, 3]
b = a
a += [4]
print("a =", a)
print("b =", b)

x = [1, 2, 3, 4]
y = [1, 2, 3]
a = [1, 2, 3, 4]
b = [1, 2, 3, 4]


ANS.13



In [ ]:
# 4
# NameError

for i in range(5):
    pass
print(i)

# A loop over range(0) does not assign j.
try:
    for j in range(0):
        pass
    print(j)
except NameError as e:
    print(type(e).__name__)

4
NameError


ANS.14


In [ ]:
# 1020
# 30
# 101010
# 3333333333
# TypeError
# 30



print("10" + "20")
print(10 + 20)
print("10" * 3)
print(10 * "3")
try:
    print("10" + 20)
except TypeError as e:
    print(type(e).__name__)
print(int("10") + 20)

1020
30
101010
3333333333
TypeError
30


ANS.15

In [ ]:

# 5
# 5
# hello
# 0
# 10
# default
# [0]



print(0 or 5)
print(5 or 0)
print(None or "hello")
print(0 and 5)
print(5 and 10)
print([] or "default")
print([0] or "default")

5
5
hello
0
10
default
[0]


## Section C — Coding



ANS.16



In [ ]:
print("Method 1: arithmetic")
a, b = 10, 20
a = a + b
b = a - b
a = a - b
print(a, b)

print("Method 2: XOR")
a, b = 10, 20
a = a ^ b
b = a ^ b
a = a ^ b
print(a, b)

print("Method 3: tuple unpacking")
a, b = 10, 20
a, b = b, a
print(a, b)

Method 1: arithmetic
20 10
Method 2: XOR
20 10
Method 3: tuple unpacking
20 10


ANS.17



In [ ]:
price = 250
quantity = 2
total = price * quantity
gst = total * 0.18
delivery = 40 if total < 500 else 0
final_amount = total + gst + delivery

print("Item Total:", total)
print("GST (18%):", gst)
print("Delivery Charge:", delivery)
print("Final Amount:", final_amount)



Item Total: 500
GST (18%): 90.0
Delivery Charge: 0
Final Amount: 590.0


ANS.18

In [ ]:
value = 25
unit = "C"

if unit.upper() == "C":
    result = (value * 9 / 5) + 32
    print("Temperature in Fahrenheit:", round(result, 2))
elif unit.upper() == "F":
    result = (value - 32) * 5 / 9                           #formula of temperature
    print("Temperature in Celsius:", round(result, 2))
else:
    print("Invalid unit")



Temperature in Fahrenheit: 77.0


ANS.19

In [ ]:
num = 4827
d1 = num // 1000
d2 = (num // 100) % 10          #operators
d3 = (num // 10) % 10
d4 = num % 10
print("Sum of digits:", d1 + d2 + d3 + d4)

Sum of digits: 21


ANS.20

In [ ]:
value = "42"
try:
    result = int(value)
    data_type = "int"
except ValueError:
    try:
        result = float(value)
        data_type = "float"
    except ValueError:
        result = value
        data_type = "str"
print("Value:", result)
print("Type:", data_type)



Value: 42
Type: int


ANS.21

In [ ]:
income = 800000
tax = 0

if income <= 300000:
    tax = 0
elif income <= 700000:
    tax = (income - 300000) * 0.05
elif income <= 1000000:
    tax = 400000 * 0.05 + (income - 700000) * 0.10
elif income <= 1200000:
    tax = 400000 * 0.05 + 300000 * 0.10 + (income - 1000000) * 0.15       #Basic maths with the use of operators
elif income <= 1500000:
    tax = 400000 * 0.05 + 300000 * 0.10 + 200000 * 0.15 + (income - 1200000) * 0.20
else:
    tax = 400000 * 0.05 + 300000 * 0.10 + 200000 * 0.15 + 300000 * 0.20 + (income - 1500000) * 0.30

print("Tax:", tax)


Tax: 30000.0


ANS.22

In [ ]:
pan = "ABCDE1234F"

if len(pan) != 10:
    print("Invalid PAN - length must be 10")
elif not pan[:5].isalpha() or not pan[:5].isupper():
    print("Invalid PAN - first 5 characters must be uppercase letters")
elif not pan[5:9].isdigit():
    print("Invalid PAN - characters 6 to 9 must be digits")    #pan card logic
elif not pan[9].isalpha() or not pan[9].isupper():
    print("Invalid PAN - last character must be an uppercase letter")
else:
    print("Valid PAN")

Valid PAN


ANS.23

In [ ]:
units = 250

if units <= 50:
    energy = units * 4.15
elif units <= 100:
    energy = 50 * 4.15 + (units - 50) * 5.60
elif units <= 200:
    energy = 50 * 4.15 + 50 * 5.60 + (units - 100) * 7.15
else:
    energy = 50 * 4.15 + 50 * 5.60 + 100 * 7.15 + (units - 200) * 8.20.    #again basic maths with operator

fixed_charge = 110
tax = (energy + fixed_charge) * 0.06
total = energy + fixed_charge + tax

print("Energy Charges:", round(energy, 2))
print("Fixed Charge:", fixed_charge)
print("Government Tax:", round(tax, 2))
print("Total Bill:", round(total, 2))

Energy Charges: 1612.5
Fixed Charge: 110
Government Tax: 103.35
Total Bill: 1825.85


ANS.24

In [ ]:
runs = 80
balls = 60

if balls == 0:
    print("Cannot calculate strike rate because balls faced is 0.")
else:
    strike_rate = (runs / balls) * 100
    print("Strike Rate:", round(strike_rate, 2))
    if strike_rate < 50:
        print("Classification: Poor")
    elif strike_rate < 80:
        print("Classification: Slow")           #strike rate = (runs/no.of ball)*100
    elif strike_rate <= 120:
        print("Classification: Good")
    else:
        print("Classification: Excellent")

Strike Rate: 133.33
Classification: Excellent


ANS.25

In [ ]:
weight = 70
height_cm = 175
height_m = height_cm / 100
bmi = weight / (height_m ** 2)
print("BMI:", round(bmi, 2))

if bmi < 18.5:
    print("Underweight")
elif bmi < 23:
    print("Normal")
elif bmi < 25:                  #bmi formula = weight/height_m**2
    print("Overweight")
elif bmi < 30:
    print("Obese")
else:
    print("Severely Obese")

BMI: 22.86
Normal


ANS.26

In [ ]:
n = 5
for i in range(1, n + 1):
    for j in range(1, i + 1):
        print(j, end="")
    print()

1
12
123
1234
12345


ANS.27

In [ ]:
n = 5
for i in range(1, n + 1):
    print(" " * (n - i), end="")
    for j in range(1, i + 1):
        print(j, end="")
    for j in range(i - 1, 0, -1):
        print(j, end="")
    print()
for i in range(n - 1, 0, -1):         # Second half of the diamond
                                      # Here i goes backwards from 4 to 1
    print(" " * (n - i), end="")
    for j in range(1, i + 1):
        print(j, end="")
    for j in range(i - 1, 0, -1):
        print(j, end="")
    print()

    1
   121
  12321
 1234321
123454321
 1234321
  12321
   121
    1


ANS.28

Only the border positions are printed with `*`.

The first and last rows are completely filled, while the middle rows contain stars only at the first and last positions.

In [ ]:
n = 5
for i in range(n):
    for j in range(n):
        if i == 0 or i == n - 1 or j == 0 or j == n - 1:
            print("*", end="")
        else:
            print(" ", end="")
    print()

*****
*   *
*   *
*   *
*****


ANS.29

In [ ]:
n = 5
for i in range(n):
    value = 1
    print(" " * (n - i - 1), end="")
    for j in range(i + 1):
        print(value, end=" ")
        value = value * (i - j) // (j + 1)        # Calculate the next value in the row
                                                  # This is the formula used to generate Pascal's Triangle
    print()


    1 
   1 1 
  1 2 1 
 1 3 3 1 
1 4 6 4 1 


ANS.30

In [ ]:
n = 5
for i in range(1, n + 1):
    for j in range(i):
        print(chr(ord("A") + j), end="")
    print()

A
AB
ABC
ABCD
ABCDE


ANS.31.

In [ ]:
armstrong = []
for num in range(1, 10000):
    digits = len(str(num))
    total = 0
    temp = num
    while temp > 0:
        digit = temp % 10
        total += digit ** digits        #formula of calculating armstrong value
        temp //= 10
    if total == num:
        armstrong.append(num)
print(", ".join(map(str, armstrong)))
print("Count:", len(armstrong))

1, 2, 3, 4, 5, 6, 7, 8, 9, 153, 370, 371, 407, 1634, 8208, 9474
Count: 16


ANS.32

In [ ]:
n = 5
a, b = 0, 1
total = 0
for _ in range(n):
    print(a, end=" ")
    total += a
    a, b = b, a + b
print()
print("Sum:", total)

0 1 1 2 3 
Sum: 7


ANS.33

In [ ]:
n = 20

def is_prime(num):
    if num < 2:
        return False
    i = 2
    while i * i <= num:
        if num % i == 0:          #prime numbers : numbers that are divisible by themselves
            return False
        i += 1
    return True

print("Prime" if is_prime(n) else "Not prime")
prime_sum = sum(num for num in range(2, n + 1) if is_prime(num))
print("Sum of primes:", prime_sum)

Not prime
Sum of primes: 77


ANS.34

In [ ]:
num = 1221
original = num
reverse = 0
while num > 0:
    digit = num % 10
    reverse = reverse * 10 + digit      #PALLINDROME - no.from front and back is same for example 1331
    num //= 10
print("Reversed:", reverse)
print("Palindrome" if original == reverse else "Not palindrome")

Reversed: 1221
Palindrome


ANS.35

In [ ]:
a, b = 48, 18
x, y = a, b
while y != 0:
    x, y = y, x % y
hcf = x
lcm = (a * b) // hcf        #formula of finding hcf
print("HCF:", hcf)
print("LCM:", lcm)

HCF: 6
LCM: 144


ANS.36

In [ ]:
sentence = "Hello Python 123!"
total_characters = len(sentence)      #cheching total characters
words = vowels = consonants = digits = spaces = special = 0
in_word = False

for ch in sentence:
    if ch.isalpha():
        if ch.lower() in "aeiou":       #present in sentence
            vowels += 1
        else:
            consonants += 1
        if not in_word:
            words += 1
            in_word = True
    elif ch.isdigit():
        digits += 1
        in_word = False
    elif ch.isspace():
        spaces += 1
        in_word = False
    else:
        special += 1            #cheching special characters
        in_word = False

print("Total characters:", total_characters)
print("Total words:", words)
print("Vowels:", vowels)
print("Consonants:", consonants)
print("Digits:", digits)
print("Spaces:", spaces)
print("Special characters:", special)

Total characters: 17
Total words: 2
Vowels: 3
Consonants: 8
Digits: 3
Spaces: 2
Special characters: 1


ANS.37

In [ ]:
marks = [78, 85, 92, 67, 74, 88, 95, 81, 69, 90]
maximum = marks[0]
minimum = marks[0]
total = 0
for mark in marks:
    if mark > maximum: maximum = mark
    if mark < minimum: minimum = mark
    total += mark
average = total / len(marks)                      #formula of finding average
above_average = sum(1 for mark in marks if mark > average)        #criteria
unique_sorted = sorted(set(marks), reverse=True)
second_highest = unique_sorted[1] if len(unique_sorted) > 1 else None
print("Maximum:", maximum)
print("Minimum:", minimum)
print("Average:", average)
print("Above average:", above_average)
print("Second highest:", second_highest)

Maximum: 95
Minimum: 67
Average: 81.9
Above average: 5
Second highest: 92


ANS.38

In [ ]:
sentence = "good food good service good food".lower()     #lower case
words = sentence.split()
frequency = {}
for word in words:
    frequency[word] = frequency.get(word, 0) + 1
sorted_words = sorted(frequency.items(), key=lambda item: item[1], reverse=True)        #using lambda function makes it easy
for word, count in sorted_words:
    print(word, ":", count)
print("Most frequent word:", sorted_words[0][0])
print("Count:", sorted_words[0][1])

good : 3
food : 2
service : 1
Most frequent word: good
Count: 3


ANS.39

In [ ]:
states = {
    "Karnataka": "Bengaluru",
    "Maharashtra": "Mumbai",
    "Delhi": "New Delhi",
    "Tamil Nadu": "Chennai",
    "Gujarat": "Gandhinagar"
}

# Add
states["Rajasthan"] = "Jaipur"
# Update
states["Delhi"] = "New Delhi"
# Search
print("Search Karnataka:", states.get("Karnataka", "Not found"))
# Delete
del states["Rajasthan"]
# Display sorted
for state in sorted(states):
    print(state, ":", states[state])


Search Karnataka: Bengaluru
Delhi : New Delhi
Gujarat : Gandhinagar
Karnataka : Bengaluru
Maharashtra : Mumbai
Tamil Nadu : Chennai


ANS.40

In [ ]:
A = {"Python", "Java", "C++", "SQL"}
B = {"Java", "JavaScript", "Python", "Go", "SQL"}
print("Both:", A & B)
print("Only A:", A - B)               #basic set operations
print("Only B:", B - A)
print("All unique:", A | B)
print("Exclusive:", A ^ B)

Both: {'SQL', 'Python', 'Java'}
Only A: {'C++'}
Only B: {'Go', 'JavaScript'}
All unique: {'SQL', 'Go', 'C++', 'Java', 'JavaScript', 'Python'}
Exclusive: {'JavaScript', 'Go', 'C++'}


ANS.41

In [ ]:
prices = (3845, 3902, 3878, 3955, 4012, 3998, 4055)
days = ("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")
maximum = max(prices)
minimum = min(prices)
average = sum(prices) / len(prices)
max_day = days[prices.index(maximum)]
min_day = days[prices.index(minimum)]

biggest_gain = prices[1] - prices[0]      #gain = selling price - cost price
gain_day = 1
for i in range(2, len(prices)):
    gain = prices[i] - prices[i - 1]
    if gain > biggest_gain:
        biggest_gain = gain
        gain_day = i

volatility = sum(abs(prices[i] - prices[i - 1]) for i in range(1, len(prices)))
print("Maximum:", maximum, max_day)
print("Minimum:", minimum, min_day)
print("Average:", round(average, 2))
print("Biggest gain:", biggest_gain)
print("Between:", days[gain_day - 1], "and", days[gain_day])
print("Total volatility:", volatility)

Maximum: 4055 Sun
Minimum: 3845 Mon
Average: 3949.29
Biggest gain: 77
Between: Wed and Thu
Total volatility: 286


ANS.42

In [ ]:
numbers = [2, 5, 7, 2, 9, 5, 10, 7, 12, 15, 20, 12, 18, 21, 25, 30, 18, 33, 40, 45]

unique_numbers = set(numbers)
duplicates = []
exactly_once = []
for num in numbers:
    count = 0
    for x in numbers:
        if x == num:
            count += 1
    if count > 1 and num not in duplicates:     #checking duplicates ifyes then append in the list
        duplicates.append(num)
    if count == 1 and num not in exactly_once:
        exactly_once.append(num)
print("Unique numbers:", unique_numbers)
print("Duplicates:", duplicates)
print("Exactly once:", exactly_once)

Unique numbers: {33, 2, 5, 7, 40, 9, 10, 12, 45, 15, 18, 20, 21, 25, 30}
Duplicates: [2, 5, 7, 12, 18]
Exactly once: [9, 10, 15, 20, 21, 25, 30, 33, 40, 45]


ANS.43

In [ ]:
sentence = "A man, a plan, a canal: Panama"
cleaned = "".join(ch.lower() for ch in sentence if ch.isalnum())
print(cleaned == cleaned[::-1])       #criteria for checking pallindrome

True


ANS.44

In [ ]:
sentence = "hello world from bengaluru"
words = sentence.split()
result = ""
for word in words:
    new_word = word[0].upper() + word[1:].lower()     #making first word of each word in upper case
    result = new_word if result == "" else result + " " + new_word
print(result)

Hello World From Bengaluru


ANS.45

In [ ]:
message = "Hello, India!"
shift = 3
result = ""
for ch in message:
    if "A" <= ch <= "Z":
        result += chr((ord(ch) - ord("A") + shift) % 26 + ord("A"))
    elif "a" <= ch <= "z":
        result += chr((ord(ch) - ord("a") + shift) % 26 + ord("a"))       # Shift the lowercase letter by 3 positions
    else:
        result += ch
print("Encrypted:", result)

Encrypted: Khoor, Lqgld!


ANS.46

In [ ]:
def calculate_gst(amount, gst_rate=18, gst_inclusive=False):
    if not gst_inclusive:
        base_amount = amount
        gst_amount = amount * gst_rate / 100
        total_amount = amount + gst_amount
    else:                                           #basic gst calculator
        total_amount = amount
        base_amount = amount / (1 + gst_rate / 100)
        gst_amount = total_amount - base_amount
    return round(base_amount, 2), round(gst_amount, 2), round(total_amount, 2)

print(calculate_gst(100))
print(calculate_gst(118, 18, True))

(100, 18.0, 118.0)
(100.0, 18.0, 118)


ANS.47

In [ ]:
def power(base, exp):
    if exp == 0:
        return 1
    if exp < 0:                         # If the exponent is negative,
                                        # calculate the positive power first
                                        # and then take its reciprocal
        return 1 / power(base, -exp)
    return base * power(base, exp - 1)

print(power(2, 10))
print(power(5, 0))
print(power(3, -2))

1024
1
0.1111111111111111


## Section C8 — NumPy

ANS.48

In [ ]:
import numpy as np

matrix = np.eye(5) * 10         #creates an identity matrix
print("Matrix:")
print(matrix)
print("Transpose:")
print(matrix.T)
print("Diagonal sum:", np.trace(matrix))
print("Total sum:", np.sum(matrix))

Matrix:
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]
Transpose:
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]
Diagonal sum: 50.0
Total sum: 50.0


ANS.49

In [ ]:
import numpy as np
sales = np.array([12000, 18500, 14200, 22100, 19800, 35200, 28400])
days = np.array(["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"])

total = np.sum(sales)
average = np.mean(sales)
max_index = np.argmax(sales)                #basic numpy functions
max_day = days[max_index]
above_average = np.sum(sales > average)
growth = ((sales[-1] - sales[0]) / sales[0]) * 100
day_changes = ((sales[1:] - sales[:-1]) / sales[:-1]) * 100

print("Total weekly sales:", total)
print("Daily average:", round(average, 2))
print("Maximum sales day:", max_day)
print("Days above average:", above_average)
print("Growth Monday to Sunday:", round(growth, 2), "%")
print("Day-on-day percentage changes:", np.round(day_changes, 2))

Total weekly sales: 150200
Daily average: 21457.14
Maximum sales day: Sat
Days above average: 3
Growth Monday to Sunday: 136.67 %
Day-on-day percentage changes: [ 54.17 -23.24  55.63 -10.41  77.78 -19.32]


ANS.50

In [ ]:
import numpy as np
matrix = np.ones((5, 5), dtype=int)   #makes matrix of ones
matrix[1:-1, 1:-1] = 0
print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
